dist: xenial
language: elixir
services:
  - docker
before_script:
  - docker-compose up -d
matrix:
  include:
    - elixir: 1.6
      otp_release: 20.0
      script:
        - MIX_ENV=test mix do deps.get, test
    - elixir: 1.11
      otp_release: 23.0
      script:
        - mix format --check-formatted
        - MIX_ENV=test mix do deps.get, credo --strict, test
branches:
  - dev
