dist: xenial
language: elixir
services:
  - docker
before_script:
  - docker-compose up -d
matrix:
  include:
    - elixir: "1.6"
      script:
        - MIX_ENV=test mix do deps.get, credo --strict, test
    - elixir: "1.12"
      script:
        - mix format --check-formatted
        - MIX_ENV=test mix do deps.get, credo --strict, test
branches:
  only:
    - master
