version: '3'
services:
  single_no_auth:
      image: arangodb/arangodb
      environment:
        - ARANGO_NO_AUTH=1
      ports:
        - '8001:8529'

  single_auth:
      image: arangodb/arangodb
      environment:
        - ARANGO_ROOT_PASSWORD=
      volumes:
        - ./test:/var/lib/arangox/test
      ports:
        - '8529:8529'
        - '8002:8530'
      command:
        - arangod
        - --server.endpoint=tcp://0.0.0.0:8529
        - --server.endpoint=ssl://0.0.0.0:8530
        - --ssl.keyfile=var/lib/arangox/test/cert.pem

  resilient_single:
      image: arangodb/arangodb
      ports:
        - '8003:8529'
        - '8004:8539'
        - '8005:8549'
      command:
        - arangodb
        - --starter.local
        - --starter.mode=activefailover