# This file is generated by priv/arangodb/gen_errno.exs from
# priv/arangodb/errors-3.12.10.dat. Do not edit it by hand.
#
#     mix run priv/arangodb/gen_errno.exs
#
defmodule Arangox.Errno do
  @moduledoc """
  ArangoDB's `errorNum` table as atoms.

  Generated from `priv/arangodb/errors-3.12.10.dat`, which is ArangoDB's
  `lib/Basics/errors.dat` vendored byte-identically at tag `3.12.10` -- the
  server release the driver is pinned to and its integration suite runs
  against; `tag/0` below is that pin. Nothing is fetched at build or run
  time.

  `Arangox.Error` carries the result of `reason/1` in its `:reason` field, so an
  application branches on an atom rather than on an integer or on the server's
  message:

      case Arangox.get(conn, "/_api/document/things/nope") do
        {:error, %Arangox.Error{reason: :arango_document_not_found}} -> :gone
        {:error, %Arangox.Error{reason: :arango_conflict}} -> :retry
      end

  ## Naming

  The atom is the published constant name with the `ERROR_` prefix stripped and
  downcased: `ERROR_ARANGO_CONFLICT` becomes `:arango_conflict`. Constant names
  are unique, so the mapping is injective; the short messages are not unique and
  are not used. This is a public pattern-matching surface and is stable.

  ## Unknown codes

  A number this table does not contain yields `:unknown`. A server newer
  than the pinned tag can introduce codes, and a caller matching on
  `%Arangox.Error{reason: reason}` must not crash or receive `nil` when it does.
  The status and the raw `errorNum` are preserved on the error either way, so
  the number is still available.

  348 codes, `0`..`21005`.
  """

  @typedoc """
  A reason atom from this table, or `:unknown` for a code the pinned
  table does not contain.
  """
  @type t :: atom

  @unknown :unknown
  @count 348

  @doc """
  The reason atom for an ArangoDB `errorNum`.

  Returns `:unknown` for any integer the pinned table does not
  contain, and for a non-integer (a server may send anything).

      iex> Arangox.Errno.reason(1202)
      :arango_document_not_found

      iex> Arangox.Errno.reason(9_999_999)
      :unknown
  """
  @spec reason(term) :: t
  def reason(0), do: :no_error
  def reason(1), do: :failed
  def reason(2), do: :sys_error
  def reason(3), do: :out_of_memory
  def reason(4), do: :internal
  def reason(5), do: :illegal_number
  def reason(6), do: :numeric_overflow
  def reason(7), do: :illegal_option
  def reason(8), do: :dead_pid
  def reason(9), do: :not_implemented
  def reason(10), do: :bad_parameter
  def reason(11), do: :forbidden
  def reason(13), do: :corrupted_csv
  def reason(14), do: :file_not_found
  def reason(15), do: :cannot_write_file
  def reason(16), do: :cannot_overwrite_file
  def reason(17), do: :type_error
  def reason(18), do: :lock_timeout
  def reason(19), do: :cannot_create_directory
  def reason(20), do: :cannot_create_temp_file
  def reason(21), do: :request_canceled
  def reason(22), do: :debug
  def reason(25), do: :ip_address_invalid
  def reason(27), do: :file_exists
  def reason(28), do: :locked
  def reason(29), do: :deadlock
  def reason(30), do: :shutting_down
  def reason(31), do: :only_enterprise
  def reason(32), do: :resource_limit
  def reason(33), do: :arango_icu_error
  def reason(34), do: :cannot_read_file
  def reason(35), do: :incompatible_version
  def reason(36), do: :disabled
  def reason(37), do: :malformed_json
  def reason(38), do: :starting_up
  def reason(39), do: :deserialize
  def reason(40), do: :end_of_file
  def reason(400), do: :http_bad_parameter
  def reason(401), do: :http_unauthorized
  def reason(403), do: :http_forbidden
  def reason(404), do: :http_not_found
  def reason(405), do: :http_method_not_allowed
  def reason(406), do: :http_not_acceptable
  def reason(408), do: :http_request_timeout
  def reason(409), do: :http_conflict
  def reason(410), do: :http_gone
  def reason(412), do: :http_precondition_failed
  def reason(420), do: :http_enhance_your_calm
  def reason(500), do: :http_server_error
  def reason(501), do: :http_not_implemented
  def reason(503), do: :http_service_unavailable
  def reason(504), do: :http_gateway_timeout
  def reason(600), do: :http_corrupted_json
  def reason(601), do: :http_superfluous_suffices
  def reason(1000), do: :arango_illegal_state
  def reason(1004), do: :arango_read_only
  def reason(1005), do: :arango_duplicate_identifier
  def reason(1100), do: :arango_corrupted_datafile
  def reason(1101), do: :arango_illegal_parameter_file
  def reason(1102), do: :arango_corrupted_collection
  def reason(1104), do: :arango_filesystem_full
  def reason(1107), do: :arango_datadir_locked
  def reason(1200), do: :arango_conflict
  def reason(1202), do: :arango_document_not_found
  def reason(1203), do: :arango_data_source_not_found
  def reason(1204), do: :arango_collection_parameter_missing
  def reason(1205), do: :arango_document_handle_bad
  def reason(1207), do: :arango_duplicate_name
  def reason(1208), do: :arango_illegal_name
  def reason(1209), do: :arango_no_index
  def reason(1210), do: :arango_unique_constraint_violated
  def reason(1212), do: :arango_index_not_found
  def reason(1213), do: :arango_cross_collection_request
  def reason(1214), do: :arango_index_handle_bad
  def reason(1216), do: :arango_document_too_large
  def reason(1218), do: :arango_collection_type_invalid
  def reason(1220), do: :arango_attribute_parser_failed
  def reason(1221), do: :arango_document_key_bad
  def reason(1222), do: :arango_document_key_unexpected
  def reason(1224), do: :arango_datadir_not_writable
  def reason(1225), do: :arango_out_of_keys
  def reason(1226), do: :arango_document_key_missing
  def reason(1227), do: :arango_document_type_invalid
  def reason(1228), do: :arango_database_not_found
  def reason(1229), do: :arango_database_name_invalid
  def reason(1230), do: :arango_use_system_database
  def reason(1232), do: :arango_invalid_key_generator
  def reason(1233), do: :arango_invalid_edge_attribute
  def reason(1235), do: :arango_index_creation_failed
  def reason(1237), do: :arango_collection_type_mismatch
  def reason(1238), do: :arango_collection_not_loaded
  def reason(1239), do: :arango_document_rev_bad
  def reason(1240), do: :arango_incomplete_read
  def reason(1241), do: :arango_old_rocksdb_format
  def reason(1242), do: :arango_index_has_legacy_sorted_keys
  def reason(1301), do: :arango_empty_datadir
  def reason(1302), do: :arango_try_again
  def reason(1303), do: :arango_busy
  def reason(1304), do: :arango_merge_in_progress
  def reason(1305), do: :arango_io_error
  def reason(1400), do: :replication_no_response
  def reason(1401), do: :replication_invalid_response
  def reason(1402), do: :replication_leader_error
  def reason(1403), do: :replication_leader_incompatible
  def reason(1404), do: :replication_leader_change
  def reason(1405), do: :replication_loop
  def reason(1406), do: :replication_unexpected_marker
  def reason(1407), do: :replication_invalid_applier_state
  def reason(1408), do: :replication_unexpected_transaction
  def reason(1409), do: :replication_shard_sync_attempt_timeout_exceeded
  def reason(1410), do: :replication_invalid_applier_configuration
  def reason(1411), do: :replication_running
  def reason(1412), do: :replication_applier_stopped
  def reason(1413), do: :replication_no_start_tick
  def reason(1414), do: :replication_start_tick_not_present
  def reason(1416), do: :replication_wrong_checksum
  def reason(1417), do: :replication_shard_nonempty
  def reason(1418), do: :replication_replicated_log_not_found
  def reason(1419), do: :replication_replicated_log_not_the_leader
  def reason(1420), do: :replication_replicated_log_not_a_follower
  def reason(1421), do: :replication_replicated_log_append_entries_rejected
  def reason(1422), do: :replication_replicated_log_leader_resigned
  def reason(1423), do: :replication_replicated_log_follower_resigned
  def reason(1424), do: :replication_replicated_log_participant_gone
  def reason(1425), do: :replication_replicated_log_invalid_term
  def reason(1426), do: :replication_replicated_log_unconfigured
  def reason(1427), do: :replication_replicated_state_not_found
  def reason(1428), do: :replication_replicated_state_not_available
  def reason(1429), do: :replication_write_concern_not_fulfilled
  def reason(1430), do: :replication_replicated_log_subsequent_fault
  def reason(1431), do: :replication_replicated_state_implementation_not_found
  def reason(1432), do: :replication_replicated_wal_error
  def reason(1433), do: :replication_replicated_wal_invalid_file
  def reason(1434), do: :replication_replicated_wal_corrupt
  def reason(1446), do: :cluster_not_follower
  def reason(1447), do: :cluster_follower_transaction_commit_performed
  def reason(1448), do: :cluster_create_collection_precondition_failed
  def reason(1449), do: :cluster_server_unknown
  def reason(1450), do: :cluster_too_many_shards
  def reason(1454), do: :cluster_could_not_create_collection_in_plan
  def reason(1456), do: :cluster_could_not_create_collection
  def reason(1457), do: :cluster_timeout
  def reason(1458), do: :cluster_could_not_remove_collection_in_plan
  def reason(1460), do: :cluster_could_not_create_database_in_plan
  def reason(1461), do: :cluster_could_not_create_database
  def reason(1462), do: :cluster_could_not_remove_database_in_plan
  def reason(1463), do: :cluster_could_not_remove_database_in_current
  def reason(1464), do: :cluster_shard_gone
  def reason(1465), do: :cluster_connection_lost
  def reason(1466), do: :cluster_must_not_specify_key
  def reason(1467), do: :cluster_got_contradicting_answers
  def reason(1468), do: :cluster_not_all_sharding_attributes_given
  def reason(1469), do: :cluster_must_not_change_sharding_attributes
  def reason(1470), do: :cluster_unsupported
  def reason(1471), do: :cluster_only_on_coordinator
  def reason(1472), do: :cluster_reading_plan_agency
  def reason(1474), do: :cluster_aql_communication
  def reason(1477), do: :cluster_only_on_dbserver
  def reason(1478), do: :cluster_backend_unavailable
  def reason(1481), do: :cluster_aql_collection_out_of_sync
  def reason(1482), do: :cluster_could_not_create_index_in_plan
  def reason(1483), do: :cluster_could_not_drop_index_in_plan
  def reason(1484), do: :cluster_chain_of_distributeshardslike
  def reason(1485), do: :cluster_must_not_drop_coll_other_distributeshardslike
  def reason(1486), do: :cluster_unknown_distributeshardslike
  def reason(1487), do: :cluster_insufficient_dbservers
  def reason(1488), do: :cluster_could_not_drop_follower
  def reason(1489), do: :cluster_shard_leader_refuses_replication
  def reason(1490), do: :cluster_shard_follower_refuses_operation
  def reason(1491), do: :cluster_shard_leader_resigned
  def reason(1492), do: :cluster_agency_communication_failed
  def reason(1495), do: :cluster_leadership_challenge_ongoing
  def reason(1496), do: :cluster_not_leader
  def reason(1497), do: :cluster_could_not_create_view_in_plan
  def reason(1498), do: :cluster_view_id_exists
  def reason(1499), do: :cluster_could_not_drop_collection
  def reason(1500), do: :query_killed
  def reason(1501), do: :query_parse
  def reason(1502), do: :query_empty
  def reason(1503), do: :query_script
  def reason(1504), do: :query_number_out_of_range
  def reason(1505), do: :query_invalid_geo_value
  def reason(1510), do: :query_variable_name_invalid
  def reason(1511), do: :query_variable_redeclared
  def reason(1512), do: :query_variable_name_unknown
  def reason(1521), do: :query_collection_lock_failed
  def reason(1522), do: :query_too_many_collections
  def reason(1524), do: :query_too_much_nesting
  def reason(1539), do: :query_invalid_options_attribute
  def reason(1540), do: :query_function_name_unknown
  def reason(1541), do: :query_function_argument_number_mismatch
  def reason(1542), do: :query_function_argument_type_mismatch
  def reason(1543), do: :query_invalid_regex
  def reason(1550), do: :query_bind_parameters_invalid
  def reason(1551), do: :query_bind_parameter_missing
  def reason(1552), do: :query_bind_parameter_undeclared
  def reason(1553), do: :query_bind_parameter_type
  def reason(1554), do: :query_vector_search_not_applied
  def reason(1555), do: :query_vector_index_not_ready
  def reason(1561), do: :query_invalid_arithmetic_value
  def reason(1562), do: :query_division_by_zero
  def reason(1563), do: :query_array_expected
  def reason(1568), do: :query_collection_used_in_expression
  def reason(1569), do: :query_fail_called
  def reason(1570), do: :query_geo_index_missing
  def reason(1571), do: :query_fulltext_index_missing
  def reason(1572), do: :query_invalid_date_value
  def reason(1573), do: :query_multi_modify
  def reason(1574), do: :query_invalid_aggregate_expression
  def reason(1575), do: :query_compile_time_options
  def reason(1576), do: :query_dnf_complexity
  def reason(1577), do: :query_forced_index_hint_unusable
  def reason(1578), do: :query_disallowed_dynamic_call
  def reason(1579), do: :query_access_after_modification
  def reason(1580), do: :query_function_invalid_name
  def reason(1581), do: :query_function_invalid_code
  def reason(1582), do: :query_function_not_found
  def reason(1583), do: :query_function_runtime_error
  def reason(1584), do: :query_not_eligible_for_plan_caching
  def reason(1590), do: :query_bad_json_plan
  def reason(1591), do: :query_not_found
  def reason(1593), do: :query_user_assert
  def reason(1594), do: :query_user_warn
  def reason(1595), do: :query_window_after_modification
  def reason(1600), do: :cursor_not_found
  def reason(1601), do: :cursor_busy
  def reason(1620), do: :validation_failed
  def reason(1621), do: :validation_bad_parameter
  def reason(1650), do: :transaction_internal
  def reason(1651), do: :transaction_nested
  def reason(1652), do: :transaction_unregistered_collection
  def reason(1653), do: :transaction_disallowed_operation
  def reason(1654), do: :transaction_aborted
  def reason(1655), do: :transaction_not_found
  def reason(1700), do: :user_invalid_name
  def reason(1702), do: :user_duplicate
  def reason(1703), do: :user_not_found
  def reason(1705), do: :user_external
  def reason(1752), do: :service_download_failed
  def reason(1753), do: :service_upload_failed
  def reason(1850), do: :task_invalid_id
  def reason(1851), do: :task_duplicate_id
  def reason(1852), do: :task_not_found
  def reason(1901), do: :graph_invalid_graph
  def reason(1906), do: :graph_invalid_edge
  def reason(1910), do: :graph_invalid_filter_result
  def reason(1920), do: :graph_collection_multi_use
  def reason(1921), do: :graph_collection_use_in_multi_graphs
  def reason(1922), do: :graph_create_missing_name
  def reason(1923), do: :graph_create_malformed_edge_definition
  def reason(1924), do: :graph_not_found
  def reason(1925), do: :graph_duplicate
  def reason(1926), do: :graph_vertex_col_does_not_exist
  def reason(1927), do: :graph_wrong_collection_type_vertex
  def reason(1928), do: :graph_not_in_orphan_collection
  def reason(1929), do: :graph_collection_used_in_edge_def
  def reason(1930), do: :graph_edge_collection_not_used
  def reason(1932), do: :graph_no_graph_collection
  def reason(1935), do: :graph_invalid_number_of_arguments
  def reason(1936), do: :graph_invalid_parameter
  def reason(1938), do: :graph_collection_used_in_orphans
  def reason(1939), do: :graph_edge_col_does_not_exist
  def reason(1940), do: :graph_empty
  def reason(1941), do: :graph_internal_data_corrupt
  def reason(1942), do: :graph_must_not_drop_collection
  def reason(1943), do: :graph_create_malformed_orphan_list
  def reason(1944), do: :graph_edge_definition_is_document
  def reason(1945), do: :graph_collection_is_initial
  def reason(1946), do: :graph_no_initial_collection
  def reason(1947), do: :graph_referenced_vertex_collection_not_part_of_the_graph
  def reason(1948), do: :graph_negative_edge_weight
  def reason(1949), do: :graph_collection_not_part_of_the_graph
  def reason(1950), do: :session_unknown
  def reason(1951), do: :session_expired
  def reason(2000), do: :simple_client_unknown_error
  def reason(2001), do: :simple_client_could_not_connect
  def reason(2002), do: :simple_client_could_not_write
  def reason(2003), do: :simple_client_could_not_read
  def reason(2019), do: :was_erlaube
  def reason(2200), do: :internal_aql
  def reason(3000), do: :malformed_manifest_file
  def reason(3001), do: :invalid_service_manifest
  def reason(3002), do: :service_files_missing
  def reason(3003), do: :service_files_outdated
  def reason(3004), do: :invalid_foxx_options
  def reason(3007), do: :invalid_mountpoint
  def reason(3009), do: :service_not_found
  def reason(3010), do: :service_needs_configuration
  def reason(3011), do: :service_mountpoint_conflict
  def reason(3012), do: :service_manifest_not_found
  def reason(3013), do: :service_options_malformed
  def reason(3014), do: :service_source_not_found
  def reason(3015), do: :service_source_error
  def reason(3016), do: :service_unknown_script
  def reason(3099), do: :service_api_disabled
  def reason(3100), do: :module_not_found
  def reason(3101), do: :module_syntax_error
  def reason(3103), do: :module_failure
  def reason(4000), do: :no_smart_collection
  def reason(4001), do: :no_smart_graph_attribute
  def reason(4002), do: :cannot_drop_smart_collection
  def reason(4003), do: :key_must_be_prefixed_with_smart_graph_attribute
  def reason(4004), do: :illegal_smart_graph_attribute
  def reason(4005), do: :smart_graph_attribute_mismatch
  def reason(4006), do: :invalid_smart_join_attribute
  def reason(4007), do: :key_must_be_prefixed_with_smart_join_attribute
  def reason(4008), do: :no_smart_join_attribute
  def reason(4009), do: :cluster_must_not_change_smart_join_attribute
  def reason(4010), do: :invalid_disjoint_smart_edge
  def reason(4011), do: :unsupported_change_in_smart_to_satellite_disjoint_edge_direction
  def reason(6003), do: :action_unfinished
  def reason(7001), do: :hot_backup_internal
  def reason(7002), do: :hot_restore_internal
  def reason(7003), do: :backup_topology
  def reason(7004), do: :no_space_left_on_device
  def reason(7005), do: :failed_to_upload_backup
  def reason(7006), do: :failed_to_download_backup
  def reason(7007), do: :no_such_hot_backup
  def reason(7008), do: :remote_repository_config_bad
  def reason(7009), do: :local_lock_failed
  def reason(7010), do: :local_lock_retry
  def reason(7011), do: :hot_backup_conflict
  def reason(7012), do: :hot_backup_dbservers_awol
  def reason(7021), do: :cluster_could_not_modify_analyzers_in_plan
  def reason(9001), do: :license_expired_or_invalid
  def reason(9002), do: :license_signature_verification
  def reason(9003), do: :license_non_matching_id
  def reason(9004), do: :license_feature_not_enabled
  def reason(9005), do: :license_resource_exhausted
  def reason(9006), do: :license_invalid
  def reason(9007), do: :license_conflict
  def reason(9008), do: :license_validation_failed
  def reason(20001), do: :agency_malformed_gossip_message
  def reason(20002), do: :agency_malformed_inquire_request
  def reason(20011), do: :agency_inform_must_be_object
  def reason(20012), do: :agency_inform_must_contain_term
  def reason(20013), do: :agency_inform_must_contain_id
  def reason(20014), do: :agency_inform_must_contain_active
  def reason(20015), do: :agency_inform_must_contain_pool
  def reason(20016), do: :agency_inform_must_contain_min_ping
  def reason(20017), do: :agency_inform_must_contain_max_ping
  def reason(20018), do: :agency_inform_must_contain_timeout_mult
  def reason(20021), do: :agency_cannot_rebuild_dbs
  def reason(20030), do: :agency_malformed_transaction
  def reason(20501), do: :supervision_general_failure
  def reason(21003), do: :queue_full
  def reason(21004), do: :queue_time_requirement_violated
  def reason(21005), do: :too_many_detached_threads
  def reason(_error_num), do: @unknown

  @doc """
  The `errorNum` for a reason atom, or `nil` for one this table does not
  contain (including `:unknown`).

      iex> Arangox.Errno.error_num(:arango_conflict)
      1200

      iex> Arangox.Errno.error_num(:unknown)
      nil
  """
  @spec error_num(t) :: integer | nil
  def error_num(:no_error), do: 0
  def error_num(:failed), do: 1
  def error_num(:sys_error), do: 2
  def error_num(:out_of_memory), do: 3
  def error_num(:internal), do: 4
  def error_num(:illegal_number), do: 5
  def error_num(:numeric_overflow), do: 6
  def error_num(:illegal_option), do: 7
  def error_num(:dead_pid), do: 8
  def error_num(:not_implemented), do: 9
  def error_num(:bad_parameter), do: 10
  def error_num(:forbidden), do: 11
  def error_num(:corrupted_csv), do: 13
  def error_num(:file_not_found), do: 14
  def error_num(:cannot_write_file), do: 15
  def error_num(:cannot_overwrite_file), do: 16
  def error_num(:type_error), do: 17
  def error_num(:lock_timeout), do: 18
  def error_num(:cannot_create_directory), do: 19
  def error_num(:cannot_create_temp_file), do: 20
  def error_num(:request_canceled), do: 21
  def error_num(:debug), do: 22
  def error_num(:ip_address_invalid), do: 25
  def error_num(:file_exists), do: 27
  def error_num(:locked), do: 28
  def error_num(:deadlock), do: 29
  def error_num(:shutting_down), do: 30
  def error_num(:only_enterprise), do: 31
  def error_num(:resource_limit), do: 32
  def error_num(:arango_icu_error), do: 33
  def error_num(:cannot_read_file), do: 34
  def error_num(:incompatible_version), do: 35
  def error_num(:disabled), do: 36
  def error_num(:malformed_json), do: 37
  def error_num(:starting_up), do: 38
  def error_num(:deserialize), do: 39
  def error_num(:end_of_file), do: 40
  def error_num(:http_bad_parameter), do: 400
  def error_num(:http_unauthorized), do: 401
  def error_num(:http_forbidden), do: 403
  def error_num(:http_not_found), do: 404
  def error_num(:http_method_not_allowed), do: 405
  def error_num(:http_not_acceptable), do: 406
  def error_num(:http_request_timeout), do: 408
  def error_num(:http_conflict), do: 409
  def error_num(:http_gone), do: 410
  def error_num(:http_precondition_failed), do: 412
  def error_num(:http_enhance_your_calm), do: 420
  def error_num(:http_server_error), do: 500
  def error_num(:http_not_implemented), do: 501
  def error_num(:http_service_unavailable), do: 503
  def error_num(:http_gateway_timeout), do: 504
  def error_num(:http_corrupted_json), do: 600
  def error_num(:http_superfluous_suffices), do: 601
  def error_num(:arango_illegal_state), do: 1000
  def error_num(:arango_read_only), do: 1004
  def error_num(:arango_duplicate_identifier), do: 1005
  def error_num(:arango_corrupted_datafile), do: 1100
  def error_num(:arango_illegal_parameter_file), do: 1101
  def error_num(:arango_corrupted_collection), do: 1102
  def error_num(:arango_filesystem_full), do: 1104
  def error_num(:arango_datadir_locked), do: 1107
  def error_num(:arango_conflict), do: 1200
  def error_num(:arango_document_not_found), do: 1202
  def error_num(:arango_data_source_not_found), do: 1203
  def error_num(:arango_collection_parameter_missing), do: 1204
  def error_num(:arango_document_handle_bad), do: 1205
  def error_num(:arango_duplicate_name), do: 1207
  def error_num(:arango_illegal_name), do: 1208
  def error_num(:arango_no_index), do: 1209
  def error_num(:arango_unique_constraint_violated), do: 1210
  def error_num(:arango_index_not_found), do: 1212
  def error_num(:arango_cross_collection_request), do: 1213
  def error_num(:arango_index_handle_bad), do: 1214
  def error_num(:arango_document_too_large), do: 1216
  def error_num(:arango_collection_type_invalid), do: 1218
  def error_num(:arango_attribute_parser_failed), do: 1220
  def error_num(:arango_document_key_bad), do: 1221
  def error_num(:arango_document_key_unexpected), do: 1222
  def error_num(:arango_datadir_not_writable), do: 1224
  def error_num(:arango_out_of_keys), do: 1225
  def error_num(:arango_document_key_missing), do: 1226
  def error_num(:arango_document_type_invalid), do: 1227
  def error_num(:arango_database_not_found), do: 1228
  def error_num(:arango_database_name_invalid), do: 1229
  def error_num(:arango_use_system_database), do: 1230
  def error_num(:arango_invalid_key_generator), do: 1232
  def error_num(:arango_invalid_edge_attribute), do: 1233
  def error_num(:arango_index_creation_failed), do: 1235
  def error_num(:arango_collection_type_mismatch), do: 1237
  def error_num(:arango_collection_not_loaded), do: 1238
  def error_num(:arango_document_rev_bad), do: 1239
  def error_num(:arango_incomplete_read), do: 1240
  def error_num(:arango_old_rocksdb_format), do: 1241
  def error_num(:arango_index_has_legacy_sorted_keys), do: 1242
  def error_num(:arango_empty_datadir), do: 1301
  def error_num(:arango_try_again), do: 1302
  def error_num(:arango_busy), do: 1303
  def error_num(:arango_merge_in_progress), do: 1304
  def error_num(:arango_io_error), do: 1305
  def error_num(:replication_no_response), do: 1400
  def error_num(:replication_invalid_response), do: 1401
  def error_num(:replication_leader_error), do: 1402
  def error_num(:replication_leader_incompatible), do: 1403
  def error_num(:replication_leader_change), do: 1404
  def error_num(:replication_loop), do: 1405
  def error_num(:replication_unexpected_marker), do: 1406
  def error_num(:replication_invalid_applier_state), do: 1407
  def error_num(:replication_unexpected_transaction), do: 1408
  def error_num(:replication_shard_sync_attempt_timeout_exceeded), do: 1409
  def error_num(:replication_invalid_applier_configuration), do: 1410
  def error_num(:replication_running), do: 1411
  def error_num(:replication_applier_stopped), do: 1412
  def error_num(:replication_no_start_tick), do: 1413
  def error_num(:replication_start_tick_not_present), do: 1414
  def error_num(:replication_wrong_checksum), do: 1416
  def error_num(:replication_shard_nonempty), do: 1417
  def error_num(:replication_replicated_log_not_found), do: 1418
  def error_num(:replication_replicated_log_not_the_leader), do: 1419
  def error_num(:replication_replicated_log_not_a_follower), do: 1420
  def error_num(:replication_replicated_log_append_entries_rejected), do: 1421
  def error_num(:replication_replicated_log_leader_resigned), do: 1422
  def error_num(:replication_replicated_log_follower_resigned), do: 1423
  def error_num(:replication_replicated_log_participant_gone), do: 1424
  def error_num(:replication_replicated_log_invalid_term), do: 1425
  def error_num(:replication_replicated_log_unconfigured), do: 1426
  def error_num(:replication_replicated_state_not_found), do: 1427
  def error_num(:replication_replicated_state_not_available), do: 1428
  def error_num(:replication_write_concern_not_fulfilled), do: 1429
  def error_num(:replication_replicated_log_subsequent_fault), do: 1430
  def error_num(:replication_replicated_state_implementation_not_found), do: 1431
  def error_num(:replication_replicated_wal_error), do: 1432
  def error_num(:replication_replicated_wal_invalid_file), do: 1433
  def error_num(:replication_replicated_wal_corrupt), do: 1434
  def error_num(:cluster_not_follower), do: 1446
  def error_num(:cluster_follower_transaction_commit_performed), do: 1447
  def error_num(:cluster_create_collection_precondition_failed), do: 1448
  def error_num(:cluster_server_unknown), do: 1449
  def error_num(:cluster_too_many_shards), do: 1450
  def error_num(:cluster_could_not_create_collection_in_plan), do: 1454
  def error_num(:cluster_could_not_create_collection), do: 1456
  def error_num(:cluster_timeout), do: 1457
  def error_num(:cluster_could_not_remove_collection_in_plan), do: 1458
  def error_num(:cluster_could_not_create_database_in_plan), do: 1460
  def error_num(:cluster_could_not_create_database), do: 1461
  def error_num(:cluster_could_not_remove_database_in_plan), do: 1462
  def error_num(:cluster_could_not_remove_database_in_current), do: 1463
  def error_num(:cluster_shard_gone), do: 1464
  def error_num(:cluster_connection_lost), do: 1465
  def error_num(:cluster_must_not_specify_key), do: 1466
  def error_num(:cluster_got_contradicting_answers), do: 1467
  def error_num(:cluster_not_all_sharding_attributes_given), do: 1468
  def error_num(:cluster_must_not_change_sharding_attributes), do: 1469
  def error_num(:cluster_unsupported), do: 1470
  def error_num(:cluster_only_on_coordinator), do: 1471
  def error_num(:cluster_reading_plan_agency), do: 1472
  def error_num(:cluster_aql_communication), do: 1474
  def error_num(:cluster_only_on_dbserver), do: 1477
  def error_num(:cluster_backend_unavailable), do: 1478
  def error_num(:cluster_aql_collection_out_of_sync), do: 1481
  def error_num(:cluster_could_not_create_index_in_plan), do: 1482
  def error_num(:cluster_could_not_drop_index_in_plan), do: 1483
  def error_num(:cluster_chain_of_distributeshardslike), do: 1484
  def error_num(:cluster_must_not_drop_coll_other_distributeshardslike), do: 1485
  def error_num(:cluster_unknown_distributeshardslike), do: 1486
  def error_num(:cluster_insufficient_dbservers), do: 1487
  def error_num(:cluster_could_not_drop_follower), do: 1488
  def error_num(:cluster_shard_leader_refuses_replication), do: 1489
  def error_num(:cluster_shard_follower_refuses_operation), do: 1490
  def error_num(:cluster_shard_leader_resigned), do: 1491
  def error_num(:cluster_agency_communication_failed), do: 1492
  def error_num(:cluster_leadership_challenge_ongoing), do: 1495
  def error_num(:cluster_not_leader), do: 1496
  def error_num(:cluster_could_not_create_view_in_plan), do: 1497
  def error_num(:cluster_view_id_exists), do: 1498
  def error_num(:cluster_could_not_drop_collection), do: 1499
  def error_num(:query_killed), do: 1500
  def error_num(:query_parse), do: 1501
  def error_num(:query_empty), do: 1502
  def error_num(:query_script), do: 1503
  def error_num(:query_number_out_of_range), do: 1504
  def error_num(:query_invalid_geo_value), do: 1505
  def error_num(:query_variable_name_invalid), do: 1510
  def error_num(:query_variable_redeclared), do: 1511
  def error_num(:query_variable_name_unknown), do: 1512
  def error_num(:query_collection_lock_failed), do: 1521
  def error_num(:query_too_many_collections), do: 1522
  def error_num(:query_too_much_nesting), do: 1524
  def error_num(:query_invalid_options_attribute), do: 1539
  def error_num(:query_function_name_unknown), do: 1540
  def error_num(:query_function_argument_number_mismatch), do: 1541
  def error_num(:query_function_argument_type_mismatch), do: 1542
  def error_num(:query_invalid_regex), do: 1543
  def error_num(:query_bind_parameters_invalid), do: 1550
  def error_num(:query_bind_parameter_missing), do: 1551
  def error_num(:query_bind_parameter_undeclared), do: 1552
  def error_num(:query_bind_parameter_type), do: 1553
  def error_num(:query_vector_search_not_applied), do: 1554
  def error_num(:query_vector_index_not_ready), do: 1555
  def error_num(:query_invalid_arithmetic_value), do: 1561
  def error_num(:query_division_by_zero), do: 1562
  def error_num(:query_array_expected), do: 1563
  def error_num(:query_collection_used_in_expression), do: 1568
  def error_num(:query_fail_called), do: 1569
  def error_num(:query_geo_index_missing), do: 1570
  def error_num(:query_fulltext_index_missing), do: 1571
  def error_num(:query_invalid_date_value), do: 1572
  def error_num(:query_multi_modify), do: 1573
  def error_num(:query_invalid_aggregate_expression), do: 1574
  def error_num(:query_compile_time_options), do: 1575
  def error_num(:query_dnf_complexity), do: 1576
  def error_num(:query_forced_index_hint_unusable), do: 1577
  def error_num(:query_disallowed_dynamic_call), do: 1578
  def error_num(:query_access_after_modification), do: 1579
  def error_num(:query_function_invalid_name), do: 1580
  def error_num(:query_function_invalid_code), do: 1581
  def error_num(:query_function_not_found), do: 1582
  def error_num(:query_function_runtime_error), do: 1583
  def error_num(:query_not_eligible_for_plan_caching), do: 1584
  def error_num(:query_bad_json_plan), do: 1590
  def error_num(:query_not_found), do: 1591
  def error_num(:query_user_assert), do: 1593
  def error_num(:query_user_warn), do: 1594
  def error_num(:query_window_after_modification), do: 1595
  def error_num(:cursor_not_found), do: 1600
  def error_num(:cursor_busy), do: 1601
  def error_num(:validation_failed), do: 1620
  def error_num(:validation_bad_parameter), do: 1621
  def error_num(:transaction_internal), do: 1650
  def error_num(:transaction_nested), do: 1651
  def error_num(:transaction_unregistered_collection), do: 1652
  def error_num(:transaction_disallowed_operation), do: 1653
  def error_num(:transaction_aborted), do: 1654
  def error_num(:transaction_not_found), do: 1655
  def error_num(:user_invalid_name), do: 1700
  def error_num(:user_duplicate), do: 1702
  def error_num(:user_not_found), do: 1703
  def error_num(:user_external), do: 1705
  def error_num(:service_download_failed), do: 1752
  def error_num(:service_upload_failed), do: 1753
  def error_num(:task_invalid_id), do: 1850
  def error_num(:task_duplicate_id), do: 1851
  def error_num(:task_not_found), do: 1852
  def error_num(:graph_invalid_graph), do: 1901
  def error_num(:graph_invalid_edge), do: 1906
  def error_num(:graph_invalid_filter_result), do: 1910
  def error_num(:graph_collection_multi_use), do: 1920
  def error_num(:graph_collection_use_in_multi_graphs), do: 1921
  def error_num(:graph_create_missing_name), do: 1922
  def error_num(:graph_create_malformed_edge_definition), do: 1923
  def error_num(:graph_not_found), do: 1924
  def error_num(:graph_duplicate), do: 1925
  def error_num(:graph_vertex_col_does_not_exist), do: 1926
  def error_num(:graph_wrong_collection_type_vertex), do: 1927
  def error_num(:graph_not_in_orphan_collection), do: 1928
  def error_num(:graph_collection_used_in_edge_def), do: 1929
  def error_num(:graph_edge_collection_not_used), do: 1930
  def error_num(:graph_no_graph_collection), do: 1932
  def error_num(:graph_invalid_number_of_arguments), do: 1935
  def error_num(:graph_invalid_parameter), do: 1936
  def error_num(:graph_collection_used_in_orphans), do: 1938
  def error_num(:graph_edge_col_does_not_exist), do: 1939
  def error_num(:graph_empty), do: 1940
  def error_num(:graph_internal_data_corrupt), do: 1941
  def error_num(:graph_must_not_drop_collection), do: 1942
  def error_num(:graph_create_malformed_orphan_list), do: 1943
  def error_num(:graph_edge_definition_is_document), do: 1944
  def error_num(:graph_collection_is_initial), do: 1945
  def error_num(:graph_no_initial_collection), do: 1946
  def error_num(:graph_referenced_vertex_collection_not_part_of_the_graph), do: 1947
  def error_num(:graph_negative_edge_weight), do: 1948
  def error_num(:graph_collection_not_part_of_the_graph), do: 1949
  def error_num(:session_unknown), do: 1950
  def error_num(:session_expired), do: 1951
  def error_num(:simple_client_unknown_error), do: 2000
  def error_num(:simple_client_could_not_connect), do: 2001
  def error_num(:simple_client_could_not_write), do: 2002
  def error_num(:simple_client_could_not_read), do: 2003
  def error_num(:was_erlaube), do: 2019
  def error_num(:internal_aql), do: 2200
  def error_num(:malformed_manifest_file), do: 3000
  def error_num(:invalid_service_manifest), do: 3001
  def error_num(:service_files_missing), do: 3002
  def error_num(:service_files_outdated), do: 3003
  def error_num(:invalid_foxx_options), do: 3004
  def error_num(:invalid_mountpoint), do: 3007
  def error_num(:service_not_found), do: 3009
  def error_num(:service_needs_configuration), do: 3010
  def error_num(:service_mountpoint_conflict), do: 3011
  def error_num(:service_manifest_not_found), do: 3012
  def error_num(:service_options_malformed), do: 3013
  def error_num(:service_source_not_found), do: 3014
  def error_num(:service_source_error), do: 3015
  def error_num(:service_unknown_script), do: 3016
  def error_num(:service_api_disabled), do: 3099
  def error_num(:module_not_found), do: 3100
  def error_num(:module_syntax_error), do: 3101
  def error_num(:module_failure), do: 3103
  def error_num(:no_smart_collection), do: 4000
  def error_num(:no_smart_graph_attribute), do: 4001
  def error_num(:cannot_drop_smart_collection), do: 4002
  def error_num(:key_must_be_prefixed_with_smart_graph_attribute), do: 4003
  def error_num(:illegal_smart_graph_attribute), do: 4004
  def error_num(:smart_graph_attribute_mismatch), do: 4005
  def error_num(:invalid_smart_join_attribute), do: 4006
  def error_num(:key_must_be_prefixed_with_smart_join_attribute), do: 4007
  def error_num(:no_smart_join_attribute), do: 4008
  def error_num(:cluster_must_not_change_smart_join_attribute), do: 4009
  def error_num(:invalid_disjoint_smart_edge), do: 4010
  def error_num(:unsupported_change_in_smart_to_satellite_disjoint_edge_direction), do: 4011
  def error_num(:action_unfinished), do: 6003
  def error_num(:hot_backup_internal), do: 7001
  def error_num(:hot_restore_internal), do: 7002
  def error_num(:backup_topology), do: 7003
  def error_num(:no_space_left_on_device), do: 7004
  def error_num(:failed_to_upload_backup), do: 7005
  def error_num(:failed_to_download_backup), do: 7006
  def error_num(:no_such_hot_backup), do: 7007
  def error_num(:remote_repository_config_bad), do: 7008
  def error_num(:local_lock_failed), do: 7009
  def error_num(:local_lock_retry), do: 7010
  def error_num(:hot_backup_conflict), do: 7011
  def error_num(:hot_backup_dbservers_awol), do: 7012
  def error_num(:cluster_could_not_modify_analyzers_in_plan), do: 7021
  def error_num(:license_expired_or_invalid), do: 9001
  def error_num(:license_signature_verification), do: 9002
  def error_num(:license_non_matching_id), do: 9003
  def error_num(:license_feature_not_enabled), do: 9004
  def error_num(:license_resource_exhausted), do: 9005
  def error_num(:license_invalid), do: 9006
  def error_num(:license_conflict), do: 9007
  def error_num(:license_validation_failed), do: 9008
  def error_num(:agency_malformed_gossip_message), do: 20001
  def error_num(:agency_malformed_inquire_request), do: 20002
  def error_num(:agency_inform_must_be_object), do: 20011
  def error_num(:agency_inform_must_contain_term), do: 20012
  def error_num(:agency_inform_must_contain_id), do: 20013
  def error_num(:agency_inform_must_contain_active), do: 20014
  def error_num(:agency_inform_must_contain_pool), do: 20015
  def error_num(:agency_inform_must_contain_min_ping), do: 20016
  def error_num(:agency_inform_must_contain_max_ping), do: 20017
  def error_num(:agency_inform_must_contain_timeout_mult), do: 20018
  def error_num(:agency_cannot_rebuild_dbs), do: 20021
  def error_num(:agency_malformed_transaction), do: 20030
  def error_num(:supervision_general_failure), do: 20501
  def error_num(:queue_full), do: 21003
  def error_num(:queue_time_requirement_violated), do: 21004
  def error_num(:too_many_detached_threads), do: 21005
  def error_num(_reason), do: nil

  @doc """
  The catch-all reason for a code absent from the pinned table.
  """
  @spec unknown() :: t
  def unknown, do: @unknown

  @doc """
  How many codes the pinned table contains.
  """
  @spec count() :: non_neg_integer
  def count, do: @count

  @doc """
  The server tag the table is pinned to.
  """
  @spec tag() :: binary
  def tag, do: "3.12.10"

  @doc """
  Every reason atom in the pinned table, sorted. Does not include
  `:unknown`.
  """
  @spec reasons() :: [t]
  def reasons do
    [
      :action_unfinished,
      :agency_cannot_rebuild_dbs,
      :agency_inform_must_be_object,
      :agency_inform_must_contain_active,
      :agency_inform_must_contain_id,
      :agency_inform_must_contain_max_ping,
      :agency_inform_must_contain_min_ping,
      :agency_inform_must_contain_pool,
      :agency_inform_must_contain_term,
      :agency_inform_must_contain_timeout_mult,
      :agency_malformed_gossip_message,
      :agency_malformed_inquire_request,
      :agency_malformed_transaction,
      :arango_attribute_parser_failed,
      :arango_busy,
      :arango_collection_not_loaded,
      :arango_collection_parameter_missing,
      :arango_collection_type_invalid,
      :arango_collection_type_mismatch,
      :arango_conflict,
      :arango_corrupted_collection,
      :arango_corrupted_datafile,
      :arango_cross_collection_request,
      :arango_data_source_not_found,
      :arango_database_name_invalid,
      :arango_database_not_found,
      :arango_datadir_locked,
      :arango_datadir_not_writable,
      :arango_document_handle_bad,
      :arango_document_key_bad,
      :arango_document_key_missing,
      :arango_document_key_unexpected,
      :arango_document_not_found,
      :arango_document_rev_bad,
      :arango_document_too_large,
      :arango_document_type_invalid,
      :arango_duplicate_identifier,
      :arango_duplicate_name,
      :arango_empty_datadir,
      :arango_filesystem_full,
      :arango_icu_error,
      :arango_illegal_name,
      :arango_illegal_parameter_file,
      :arango_illegal_state,
      :arango_incomplete_read,
      :arango_index_creation_failed,
      :arango_index_handle_bad,
      :arango_index_has_legacy_sorted_keys,
      :arango_index_not_found,
      :arango_invalid_edge_attribute,
      :arango_invalid_key_generator,
      :arango_io_error,
      :arango_merge_in_progress,
      :arango_no_index,
      :arango_old_rocksdb_format,
      :arango_out_of_keys,
      :arango_read_only,
      :arango_try_again,
      :arango_unique_constraint_violated,
      :arango_use_system_database,
      :backup_topology,
      :bad_parameter,
      :cannot_create_directory,
      :cannot_create_temp_file,
      :cannot_drop_smart_collection,
      :cannot_overwrite_file,
      :cannot_read_file,
      :cannot_write_file,
      :cluster_agency_communication_failed,
      :cluster_aql_collection_out_of_sync,
      :cluster_aql_communication,
      :cluster_backend_unavailable,
      :cluster_chain_of_distributeshardslike,
      :cluster_connection_lost,
      :cluster_could_not_create_collection,
      :cluster_could_not_create_collection_in_plan,
      :cluster_could_not_create_database,
      :cluster_could_not_create_database_in_plan,
      :cluster_could_not_create_index_in_plan,
      :cluster_could_not_create_view_in_plan,
      :cluster_could_not_drop_collection,
      :cluster_could_not_drop_follower,
      :cluster_could_not_drop_index_in_plan,
      :cluster_could_not_modify_analyzers_in_plan,
      :cluster_could_not_remove_collection_in_plan,
      :cluster_could_not_remove_database_in_current,
      :cluster_could_not_remove_database_in_plan,
      :cluster_create_collection_precondition_failed,
      :cluster_follower_transaction_commit_performed,
      :cluster_got_contradicting_answers,
      :cluster_insufficient_dbservers,
      :cluster_leadership_challenge_ongoing,
      :cluster_must_not_change_sharding_attributes,
      :cluster_must_not_change_smart_join_attribute,
      :cluster_must_not_drop_coll_other_distributeshardslike,
      :cluster_must_not_specify_key,
      :cluster_not_all_sharding_attributes_given,
      :cluster_not_follower,
      :cluster_not_leader,
      :cluster_only_on_coordinator,
      :cluster_only_on_dbserver,
      :cluster_reading_plan_agency,
      :cluster_server_unknown,
      :cluster_shard_follower_refuses_operation,
      :cluster_shard_gone,
      :cluster_shard_leader_refuses_replication,
      :cluster_shard_leader_resigned,
      :cluster_timeout,
      :cluster_too_many_shards,
      :cluster_unknown_distributeshardslike,
      :cluster_unsupported,
      :cluster_view_id_exists,
      :corrupted_csv,
      :cursor_busy,
      :cursor_not_found,
      :dead_pid,
      :deadlock,
      :debug,
      :deserialize,
      :disabled,
      :end_of_file,
      :failed,
      :failed_to_download_backup,
      :failed_to_upload_backup,
      :file_exists,
      :file_not_found,
      :forbidden,
      :graph_collection_is_initial,
      :graph_collection_multi_use,
      :graph_collection_not_part_of_the_graph,
      :graph_collection_use_in_multi_graphs,
      :graph_collection_used_in_edge_def,
      :graph_collection_used_in_orphans,
      :graph_create_malformed_edge_definition,
      :graph_create_malformed_orphan_list,
      :graph_create_missing_name,
      :graph_duplicate,
      :graph_edge_col_does_not_exist,
      :graph_edge_collection_not_used,
      :graph_edge_definition_is_document,
      :graph_empty,
      :graph_internal_data_corrupt,
      :graph_invalid_edge,
      :graph_invalid_filter_result,
      :graph_invalid_graph,
      :graph_invalid_number_of_arguments,
      :graph_invalid_parameter,
      :graph_must_not_drop_collection,
      :graph_negative_edge_weight,
      :graph_no_graph_collection,
      :graph_no_initial_collection,
      :graph_not_found,
      :graph_not_in_orphan_collection,
      :graph_referenced_vertex_collection_not_part_of_the_graph,
      :graph_vertex_col_does_not_exist,
      :graph_wrong_collection_type_vertex,
      :hot_backup_conflict,
      :hot_backup_dbservers_awol,
      :hot_backup_internal,
      :hot_restore_internal,
      :http_bad_parameter,
      :http_conflict,
      :http_corrupted_json,
      :http_enhance_your_calm,
      :http_forbidden,
      :http_gateway_timeout,
      :http_gone,
      :http_method_not_allowed,
      :http_not_acceptable,
      :http_not_found,
      :http_not_implemented,
      :http_precondition_failed,
      :http_request_timeout,
      :http_server_error,
      :http_service_unavailable,
      :http_superfluous_suffices,
      :http_unauthorized,
      :illegal_number,
      :illegal_option,
      :illegal_smart_graph_attribute,
      :incompatible_version,
      :internal,
      :internal_aql,
      :invalid_disjoint_smart_edge,
      :invalid_foxx_options,
      :invalid_mountpoint,
      :invalid_service_manifest,
      :invalid_smart_join_attribute,
      :ip_address_invalid,
      :key_must_be_prefixed_with_smart_graph_attribute,
      :key_must_be_prefixed_with_smart_join_attribute,
      :license_conflict,
      :license_expired_or_invalid,
      :license_feature_not_enabled,
      :license_invalid,
      :license_non_matching_id,
      :license_resource_exhausted,
      :license_signature_verification,
      :license_validation_failed,
      :local_lock_failed,
      :local_lock_retry,
      :lock_timeout,
      :locked,
      :malformed_json,
      :malformed_manifest_file,
      :module_failure,
      :module_not_found,
      :module_syntax_error,
      :no_error,
      :no_smart_collection,
      :no_smart_graph_attribute,
      :no_smart_join_attribute,
      :no_space_left_on_device,
      :no_such_hot_backup,
      :not_implemented,
      :numeric_overflow,
      :only_enterprise,
      :out_of_memory,
      :query_access_after_modification,
      :query_array_expected,
      :query_bad_json_plan,
      :query_bind_parameter_missing,
      :query_bind_parameter_type,
      :query_bind_parameter_undeclared,
      :query_bind_parameters_invalid,
      :query_collection_lock_failed,
      :query_collection_used_in_expression,
      :query_compile_time_options,
      :query_disallowed_dynamic_call,
      :query_division_by_zero,
      :query_dnf_complexity,
      :query_empty,
      :query_fail_called,
      :query_forced_index_hint_unusable,
      :query_fulltext_index_missing,
      :query_function_argument_number_mismatch,
      :query_function_argument_type_mismatch,
      :query_function_invalid_code,
      :query_function_invalid_name,
      :query_function_name_unknown,
      :query_function_not_found,
      :query_function_runtime_error,
      :query_geo_index_missing,
      :query_invalid_aggregate_expression,
      :query_invalid_arithmetic_value,
      :query_invalid_date_value,
      :query_invalid_geo_value,
      :query_invalid_options_attribute,
      :query_invalid_regex,
      :query_killed,
      :query_multi_modify,
      :query_not_eligible_for_plan_caching,
      :query_not_found,
      :query_number_out_of_range,
      :query_parse,
      :query_script,
      :query_too_many_collections,
      :query_too_much_nesting,
      :query_user_assert,
      :query_user_warn,
      :query_variable_name_invalid,
      :query_variable_name_unknown,
      :query_variable_redeclared,
      :query_vector_index_not_ready,
      :query_vector_search_not_applied,
      :query_window_after_modification,
      :queue_full,
      :queue_time_requirement_violated,
      :remote_repository_config_bad,
      :replication_applier_stopped,
      :replication_invalid_applier_configuration,
      :replication_invalid_applier_state,
      :replication_invalid_response,
      :replication_leader_change,
      :replication_leader_error,
      :replication_leader_incompatible,
      :replication_loop,
      :replication_no_response,
      :replication_no_start_tick,
      :replication_replicated_log_append_entries_rejected,
      :replication_replicated_log_follower_resigned,
      :replication_replicated_log_invalid_term,
      :replication_replicated_log_leader_resigned,
      :replication_replicated_log_not_a_follower,
      :replication_replicated_log_not_found,
      :replication_replicated_log_not_the_leader,
      :replication_replicated_log_participant_gone,
      :replication_replicated_log_subsequent_fault,
      :replication_replicated_log_unconfigured,
      :replication_replicated_state_implementation_not_found,
      :replication_replicated_state_not_available,
      :replication_replicated_state_not_found,
      :replication_replicated_wal_corrupt,
      :replication_replicated_wal_error,
      :replication_replicated_wal_invalid_file,
      :replication_running,
      :replication_shard_nonempty,
      :replication_shard_sync_attempt_timeout_exceeded,
      :replication_start_tick_not_present,
      :replication_unexpected_marker,
      :replication_unexpected_transaction,
      :replication_write_concern_not_fulfilled,
      :replication_wrong_checksum,
      :request_canceled,
      :resource_limit,
      :service_api_disabled,
      :service_download_failed,
      :service_files_missing,
      :service_files_outdated,
      :service_manifest_not_found,
      :service_mountpoint_conflict,
      :service_needs_configuration,
      :service_not_found,
      :service_options_malformed,
      :service_source_error,
      :service_source_not_found,
      :service_unknown_script,
      :service_upload_failed,
      :session_expired,
      :session_unknown,
      :shutting_down,
      :simple_client_could_not_connect,
      :simple_client_could_not_read,
      :simple_client_could_not_write,
      :simple_client_unknown_error,
      :smart_graph_attribute_mismatch,
      :starting_up,
      :supervision_general_failure,
      :sys_error,
      :task_duplicate_id,
      :task_invalid_id,
      :task_not_found,
      :too_many_detached_threads,
      :transaction_aborted,
      :transaction_disallowed_operation,
      :transaction_internal,
      :transaction_nested,
      :transaction_not_found,
      :transaction_unregistered_collection,
      :type_error,
      :unsupported_change_in_smart_to_satellite_disjoint_edge_direction,
      :user_duplicate,
      :user_external,
      :user_invalid_name,
      :user_not_found,
      :validation_bad_parameter,
      :validation_failed,
      :was_erlaube
    ]
  end
end
