# Generator for `Arangox.Errno`, the ArangoDB `errorNum` table.
#
# Reads the vendored, byte-identical upstream error table and writes
# `lib/arangox/errno.ex`. The vendored copy is never modified: this script is
# the only sanctioned way to turn it into Elixir, so the difference between what
# ArangoDB publishes and what we compile is visible in one place.
#
# Run with:
#
#     mix run priv/arangodb/gen_errno.exs
#
# The generated module is committed. Nothing is fetched from the
# network at build or run time.
#
# ## Reason-atom naming
#
# `ERROR_ARANGO_CONFLICT` -> `:arango_conflict`: strip the `ERROR_` prefix and
# downcase. The constant names are unique and are already snake-shaped, so the
# mapping is injective and stable. The short messages are deliberately *not*
# used -- they are not unique and contain spaces and format specifiers.
#
# ## Unknown codes
#
# A number absent from the table yields `:unknown`. A newer server introducing
# codes therefore cannot crash a caller or hand it a `nil` reason. `:unknown` is
# asserted below not to collide with any generated atom.

vendored = Path.join(__DIR__, "errors-3.12.10.dat")
generated = Path.expand("../../lib/arangox/errno.ex", __DIR__)

tag = "3.12.10"
unknown = :unknown

# The pinned table's digest. Re-pinning is a deliberate act that updates this
# value, the filename above and priv/arangodb/README.md together, alongside
# the docker-compose.yml server default — `tag` below feeds `Errno.tag/0`,
# the version pin the API conformance gate asserts against the live server
# (see "Updating to a new server tag" in AGENTS.md).
expected_sha256 = "64397475bfe2c988ca42389bed44a57679d8bbdcef0cd6dad6ad899999c9d13f"

raw = File.read!(vendored)
actual_sha256 = :crypto.hash(:sha256, raw) |> Base.encode16(case: :lower)

if actual_sha256 != expected_sha256 do
  Mix.raise("""
  Vendored ArangoDB error table does not match its pinned digest.

    file:     #{vendored}
    expected: #{expected_sha256}
    actual:   #{actual_sha256}

  The vendored table must stay byte-identical to what ArangoDB publishes at tag
  #{tag}. Never hand-edit it. If you are intentionally re-pinning to a new
  server tag, update expected_sha256 here and the pin recorded in
  priv/arangodb/README.md.
  """)
end

entries =
  raw
  |> String.split("\n")
  |> Enum.filter(&String.starts_with?(&1, "ERROR_"))
  |> Enum.map(fn line ->
    [constant, number | _rest] = String.split(line, ",", parts: 3)
    {constant, String.to_integer(number)}
  end)

if entries == [] do
  Mix.raise("no entries parsed from #{vendored}")
end

reason_for = fn "ERROR_" <> rest -> rest |> String.downcase() |> String.to_atom() end

table = Enum.map(entries, fn {constant, number} -> {number, reason_for.(constant)} end)

# Post-conditions. Any of these failing means the table changed shape and the
# generated module would be silently wrong.
duplicate = fn list ->
  list |> Enum.frequencies() |> Enum.filter(fn {_k, n} -> n > 1 end) |> Enum.map(&elem(&1, 0))
end

case duplicate.(Enum.map(table, &elem(&1, 0))) do
  [] -> :ok
  dupes -> Mix.raise("duplicate errorNum values in the table: #{inspect(dupes)}")
end

case duplicate.(Enum.map(table, &elem(&1, 1))) do
  [] -> :ok
  dupes -> Mix.raise("reason-atom collision: #{inspect(dupes)}")
end

if unknown in Enum.map(table, &elem(&1, 1)) do
  Mix.raise("""
  the catch-all reason #{inspect(unknown)} collides with a generated reason. Pick
  a different catch-all here and in Arangox.Error's documentation.
  """)
end

case Enum.reject(table, fn {_n, reason} ->
       Regex.match?(~r/^[a-z][a-z0-9_]*$/, Atom.to_string(reason))
     end) do
  [] -> :ok
  bad -> Mix.raise("reason atoms are not plain snake_case identifiers: #{inspect(bad)}")
end

sorted = Enum.sort_by(table, &elem(&1, 0))

reason_clauses =
  Enum.map_join(sorted, "\n", fn {number, reason} ->
    "  def reason(#{number}), do: #{inspect(reason)}"
  end)

error_num_clauses =
  Enum.map_join(sorted, "\n", fn {number, reason} ->
    "  def error_num(#{inspect(reason)}), do: #{number}"
  end)

reasons_list =
  sorted
  |> Enum.map(&elem(&1, 1))
  |> Enum.sort()
  |> Enum.map_join(",\n", &"    #{inspect(&1)}")

module = """
# This file is generated by priv/arangodb/gen_errno.exs from
# priv/arangodb/errors-#{tag}.dat. Do not edit it by hand.
#
#     mix run priv/arangodb/gen_errno.exs
#
defmodule Arangox.Errno do
  @moduledoc \"\"\"
  ArangoDB's `errorNum` table as atoms.

  Generated from `priv/arangodb/errors-#{tag}.dat`, which is ArangoDB's
  `lib/Basics/errors.dat` vendored byte-identically at tag `#{tag}` -- the
  server release the driver is pinned to and its integration suite runs
  against; `tag/0` below is that pin. Nothing is fetched at build or run
  time.

  `Arangox.Error` carries the result of `reason/1` in its `:reason` field, so an
  application branches on an atom rather than on an integer or on the server's
  message:

      case Arangox.get(conn, "/_api/document/things/nope") do
        {:error, %Arangox.Error{reason: :arango_document_not_found}} -> :gone
        {:error, %Arangox.Error{reason: :arango_conflict}} -> :retry
      end

  ## Naming

  The atom is the published constant name with the `ERROR_` prefix stripped and
  downcased: `ERROR_ARANGO_CONFLICT` becomes `:arango_conflict`. Constant names
  are unique, so the mapping is injective; the short messages are not unique and
  are not used. This is a public pattern-matching surface and is stable.

  ## Unknown codes

  A number this table does not contain yields `#{inspect(unknown)}`. A server newer
  than the pinned tag can introduce codes, and a caller matching on
  `%Arangox.Error{reason: reason}` must not crash or receive `nil` when it does.
  The status and the raw `errorNum` are preserved on the error either way, so
  the number is still available.

  #{length(sorted)} codes, `#{List.first(sorted) |> elem(0)}`..`#{List.last(sorted) |> elem(0)}`.
  \"\"\"

  @typedoc \"\"\"
  A reason atom from this table, or `#{inspect(unknown)}` for a code the pinned
  table does not contain.
  \"\"\"
  @type t :: atom

  @unknown #{inspect(unknown)}
  @count #{length(sorted)}

  @doc \"\"\"
  The reason atom for an ArangoDB `errorNum`.

  Returns `#{inspect(unknown)}` for any integer the pinned table does not
  contain, and for a non-integer (a server may send anything).

      iex> Arangox.Errno.reason(1202)
      :arango_document_not_found

      iex> Arangox.Errno.reason(9_999_999)
      #{inspect(unknown)}
  \"\"\"
  @spec reason(term) :: t
#{reason_clauses}
  def reason(_error_num), do: @unknown

  @doc \"\"\"
  The `errorNum` for a reason atom, or `nil` for one this table does not
  contain (including `#{inspect(unknown)}`).

      iex> Arangox.Errno.error_num(:arango_conflict)
      1200

      iex> Arangox.Errno.error_num(#{inspect(unknown)})
      nil
  \"\"\"
  @spec error_num(t) :: integer | nil
#{error_num_clauses}
  def error_num(_reason), do: nil

  @doc \"\"\"
  The catch-all reason for a code absent from the pinned table.
  \"\"\"
  @spec unknown() :: t
  def unknown, do: @unknown

  @doc \"\"\"
  How many codes the pinned table contains.
  \"\"\"
  @spec count() :: non_neg_integer
  def count, do: @count

  @doc \"\"\"
  The server tag the table is pinned to.
  \"\"\"
  @spec tag() :: binary
  def tag, do: "#{tag}"

  @doc \"\"\"
  Every reason atom in the pinned table, sorted. Does not include
  `#{inspect(unknown)}`.
  \"\"\"
  @spec reasons() :: [t]
  def reasons do
    [
#{reasons_list}
    ]
  end
end
"""

# Formatted before writing, not formatted after the fact: CI runs
# `mix format --check-formatted`, and this module is regenerated rather
# than edited, so a generator emitting unformatted source would break the build
# on every refresh. Uses the project's own .formatter.exs so the output matches
# what `mix format` would produce.
formatted =
  module
  |> Code.format_string!(file: generated)
  |> IO.iodata_to_binary()

File.write!(generated, formatted <> "\n")

IO.puts("""
Generated Arangox.Errno
  source:    #{Path.relative_to_cwd(vendored)} (sha256 #{String.slice(actual_sha256, 0, 12)}...)
  tag:       #{tag}
  output:    #{Path.relative_to_cwd(generated)}
  codes:     #{length(sorted)} (#{List.first(sorted) |> elem(0)}..#{List.last(sorted) |> elem(0)})
  catch-all: #{inspect(unknown)}
""")
